# https://taskfile.dev

version: '3'

tasks:
  init:
    cmds:
      - rustup target add x86_64-unknown-linux-musl
      - rustup target add aarch64-unknown-linux-musl
      - cargo install --locked cargo-zigbuild
  build:
    cmds:
      - cargo zigbuild --release --target x86_64-unknown-linux-musl
      - cargo zigbuild --release --target aarch64-unknown-linux-musl
  clean:
    cmds:
      - cargo clean
