name: Pre-build Devcontainer

on:
  push:
    branches:
      - main
    paths: 
      - .github/.devcontainer/**

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        env:
          # ref. https://github.com/containers/skopeo/issues/1874
          BUILDX_NO_DEFAULT_ATTESTATIONS: "1"
        with:
          subFolder: .github
          platform: linux/amd64
          imageName: ghcr.io/${{ github.repository }}-devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          push: always
