name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

defaults:
  run:
    shell: bash -ile {0}

env:
  BIN: volume-init-s3-objects

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:latest
    steps:
      - uses: actions/checkout@v4
      - run: task init
      - run: task build
      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          REPO="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
          git config --global --add safe.directory /__w/$REPO/$REPO
          mv target/x86_64-unknown-linux-musl/release/$BIN $BIN-amd64
          mv target/aarch64-unknown-linux-musl/release/$BIN $BIN-arm64
          gh release upload ${{ github.event.release.tag_name }} $BIN-amd64 $BIN-arm64
