name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

defaults:
  run:
    shell: bash -ile {0}

env:
  BIN: volume-init-s3-objects

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:latest
    steps:
      - uses: actions/checkout@v4
      - run: task init
      - run: task build
      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          REPO="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
          git config --global --add safe.directory /__w/$REPO/$REPO
          cp target/x86_64-unknown-linux-musl/release/$BIN /tmp/$BIN-amd64
          cp target/aarch64-unknown-linux-musl/release/$BIN /tmp/$BIN-arm64
          gh release upload ${{ github.event.release.tag_name }} /tmp/$BIN-amd64 /tmp/$BIN-arm64
      # Build and push the Docker image
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
